routingRules:
  - domain: "beckn.one:deg:ev-charging:2.0.0"
    version: "2.0.0"
    targetType: "bpp"
    # target:
    #   url: "http://onix-bpp:8082/bpp/receiver/"
    endpoints:
      - select
      - init
      - confirm
      - status
      - track
      - cancel
      - update
      - rating
      - support

  - domain: "beckn.one:deg:ev-charging:2.0.0"
    version: "2.0.0"
    targetType: "url"
    target:
      url: "https://34.93.141.21.sslip.io/beckn"
    endpoints:
      - discover
