routingRules:
  - domain: "beckn.one:deg:ev-charging:2.0.0"
    version: "2.0.0"
    targetType: "url"
    target:
      url: "http://tunnel:8083/tunnel/callback/"
    endpoints:
      - on_discover
      - on_select
      - on_init
      - on_confirm
      - on_status
      - on_track
      - on_cancel
      - on_update
      - on_rating
      - on_support
